GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9tbXkiLCJpYXQiOjE2OTg4NjMwNzEsImV4cCI6MTY5ODg2MzEzMX0.1uQmHoammNfGOPeykQA1VLRin8v-OX7ybdT4aqJUsTc

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9tbXkiLCJpYXQiOjE2Nzk4ODUyNjQsImV4cCI6MTY3OTg4NTM1NH0.Fl_2LPKuAYCxUTOXXbAVF65utugZKyeNqEmZoqRnRQk"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9tbXkiLCJpYXQiOjE2OTg4NjMxOTJ9.e0Ihyla0DvTZ-tPoOduUXr-3unRECWdKo-LAcPsJUR4"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Tommy"
}