@host=http://localhost:8000

# Home page
GET {{host}}/hello/ HTTP/1.1

###
# Get Headers
GET {{host}}/hello/headers HTTP/1.1
###
POST {{host}}/hello/headers HTTP/1.1
Content-Type: application/json
Cookie: csrftoken=sm70E4k6Gy2NMzkvzcCibaIkydDN3ggk
X-CSRFToken: sm70E4k6Gy2NMzkvzcCibaIkydDN3ggk

###
# POST data
POST {{host}}/hello/data HTTP/1.1
Content-Type: application/json
Content-Length: 18
Cookie: csrftoken=sm70E4k6Gy2NMzkvzcCibaIkydDN3ggk
X-CSRFToken: sm70E4k6Gy2NMzkvzcCibaIkydDN3ggk

{"data":"Hello Django POST!"}

###
# GET data
GET {{host}}/hello/data?message=hellodjangoGET&role=student HTTP/1.1
