
### Get user list
GET http://localhost:3000/users

### Create user

POST http://localhost:3000/users/create
Content-Type: application/json

{
  "username": "Tommy",
  "password": "WebDev"
}

### Successful login

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "Tommy",
  "password": "WebDev"
}

### Failed login

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "Tommy",
  "password": "web_dev"
}